# Generated by Django 3.1.3 on 2021-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumps_counter', models.IntegerField(default=0)),
                ('jumps_forward', models.IntegerField(default=0)),
                ('jumps_backward', models.IntegerField(default=0)),
            ],
        ),
    ]
