# Generated by Django 3.2 on 2021-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0004_rename_id_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name=''),
        ),
    ]
