# Generated by Django 3.2 on 2021-05-19 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0005_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 15, 0, 57, 580793)),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Новый проект <django.db.models.fields.IntegerField>'),
        ),
    ]
