# Generated by Django 3.2 on 2021-05-23 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0006_auto_20210519_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 19, 47, 9, 128857)),
        ),
        migrations.AlterField(
            model_name='session',
            name='kuz_place',
            field=models.IntegerField(default=0),
        ),
    ]
