# Generated by Django 4.2.1 on 2023-05-31 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0009_alter_session_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 17, 35, 38, 656200)),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
