# Generated by Django 4.2.1 on 2023-05-31 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0010_alter_session_creationdate_alter_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 17, 37, 51, 619026)),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Новый проект <django.db.models.fields.AutoField>'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
