# Generated by Django 4.2.2 on 2023-06-12 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0011_alter_session_creationdate_alter_session_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 5, 30, 13, 277444)),
        ),
    ]
